backend:
  name: github
  repo: deslee/des-portfolio-test-1

media_folder: static/img
public_folder: /img

collections:
  - name: "video"
    label: "Videos"
    folder: "src/pages/video-post"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: 
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "video-post"}
      - {label: "Path (must begin with a '/')", name: "path", widget: "string" }
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Video", name: "video", widget: "string"}
      - {label: "Tags", name: "tags", widget: list }
      - {label: "Body", name: "body", widget: "markdown"}
      
  - name: "image"
    label: "Images"
    folder: "src/pages/image-post"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: 
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "image-post"}
      - {label: "Path (must begin with a '/')", name: "path", widget: "string" }
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image"}
      - {label: "Images", name: "images", widget: list, fields: [{label: "Image", name: "image", widget: "image"},{label: "Description", name: "description"}] }
      - {label: "Tags", name: "tags", widget: list }
      - {label: "Body", name: "body", widget: "markdown"}